config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'courses/index'

  resources :courses do
    member do
      patch 'course_restore'
    end
  end

  root 'toppage#index'
  get 'create'    => 'courses#new'
  get 'all'       => 'courses#index'
  get 'search'    => 'toppage#search'
  get 'cate_search' => 'toppage#cate_search'
  get 'course' => 'courses#show'
  get 'deleted' => 'courses#discarded'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # define errors
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  include Discard::Model
  default_scope -> { kept } # return all records without discarded records
  validates :day_length, presence: true
  validates :course_id, uniqueness: true, length: { maximum: 20, too_long: '%{count} characters is the maximum allowed' }
  validates :course_title, presence: true, length: { maximum: 50, too_long: '%{count} characters is the maximum allowed' }
  validates :topic, presence: true, length: { maximum: 100, too_long: '%{count} characters is the maximum allowed' }
  validates :category, presence: true, length: { maximum: 40, too_long: '%{count} characters is the maximum allowed' }
  validates :level_id, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 999_999 }
  self.table_name = 'course' # use existing table
end

Course.all             # => Only kept Course
Course.kept            # => same to Course.all
Course.discarded       # => []
Course.with_discarded            # All course
Course.with_discarded.discarded  # Only discarded course

# discard
course = Course.first # => #<Course id: 1, ...>
course.discard        # => true
course.discard!       # => Discard::RecordNotDiscarded: Failed to discard the record
course.discarded?     # => true
course.kept?          # => false

Course.all             # => [#<Course id: 1, ...>]
Course.kept            # => []
Course.discarded       # => [#<Course id: 1, ...>]

# undiscard
course = Course.first # => #<Post id: 1, ...>
course.undiscard      # => true
course.undiscard!     # => Discard::RecordNotUndiscarded: Failed to undiscard the record
course.discarded_at   # => nil

app/models/toppage.rb
class Toppage < ApplicationRecord

# define search method
def self.search(search)
    if search.blank?  # blank? covers both nil and empty string
        all
    else
        Course.all
    end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy course_restore]
  include CoursesHelper

  # GET /courses
  # GET /courses.json
  def index
    # @courses = Course.all
    @courses = Course.paginate(page: params[:page], per_page: 15).order(sort_column + ' ' + sort_direction)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.discard
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def course_restore
    @course = Course.with_discarded.discarded.find(params[:id]).undiscard
    redirect_to deleted_path, notice: 'Course was successfully restored.'
  end

  def discarded
    @courses = Course.with_discarded.discarded
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.with_discarded.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:course_id, :course_title, :topic, :day_length, :price, :level_id, :category)
  end
end

app/controllers/toppage_controller.rb
# frozen_string_literal: true

class ToppageController < ApplicationController
  include ToppageHelper

  def index
    @cates = Course.distinct.select(:category)
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: 'Empty Keyword!') and return
    else
      @keyword = params[:search].downcase
      split_keyword = @keyword.split(/[[:blank:]]+/)
      @keyword_results = []
      split_keyword.each do |kw|
        next if kw == ''
        
        @keyword_results += Course.all.where("lower(course_title) LIKE :search OR \
                lower(topic) LIKE :search OR lower(category) LIKE :search", search: "%#{kw}%").order(sort_column + ' ' + sort_direction)
      end
      @keyword_results.uniq!
    end
  end

  def cate_search
    if params[:category_name].blank?
      redirect_to(root_path, alert: 'Empty Category!') and return
    else
      @param = params[:category_name]
      @cates_res = Course.all.where('category=?', @param).order(sort_column + ' ' + sort_direction)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # 根据所在的页面返回完整的标题
  def full_title(page_title = '')
    base_title = 'Training DB Webapp'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
  def sort_asc(column_to_be_sorted)
    link_to '▲', { column: column_to_be_sorted, direction: 'asc' }
  end

  def sort_desc(column_to_be_sorted)
    link_to '▼', { column: column_to_be_sorted, direction: 'desc' }
  end

  def sort_direction
    # If params[:direction] is nil, set sort_direction to "desc" by default
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_column
    # If params[:column] is nil, set sort_column to "occurred_date" by default
    Course.column_names.include?(params[:column]) ? params[:column] : 'course_id'
  end
end

app/helpers/toppage_helper.rb
# frozen_string_literal: true

module ToppageHelper
  def sort_asc(column_to_be_sorted)
    link_to '▲', { column: column_to_be_sorted, direction: 'asc' }
  end

  def sort_desc(column_to_be_sorted)
    link_to '▼', { column: column_to_be_sorted, direction: 'desc' }
  end

  def sort_direction
    # If params[:direction] is nil, set sort_direction to "desc" by default
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    # If params[:column] is nil, set sort_column to "occurred_date" by default
    Course.column_names.include?(params[:column]) ? params[:column] : 'course_id'
  end
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :course_title %>
    <%= form.text_field :course_title %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :day_length %>
    <%= form.number_field :day_length %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :level_id %>
    <%= form.number_field :level_id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/discarded.html.erb
<p id="notice"><%= notice %></p>
<h1>Deleted Course</h1>

<table table class="table table-striped">
  <thead>
    <tr>
      <th>Course ID></th>
      <th>Course title</th>
      <th>Topic</th>
      <th>Day length</th>
      <th>Price</th>
      <th>Level</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_id %></td>
        <td><%= course.course_title %></td>
        <td><%= course.topic %></td>
        <td><%= course.day_length %></td>
        <td><%= course.price %></td>
        <td><%= course.level_id %></td>
        <td><%= course.category %></td>
        <td><%= link_to "Restore", course_restore_course_path(course), method: :patch, class: 'btn btn-info'%>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1></h1>
<%= link_to 'Back',courses_path, class: "back_btn" %> 

app/views/courses/edit.html.erb
<h1>Update Course</h1>

<% if @course.errors.any? %>
 <div id="error_explanation">
 <div class="alert alert-danger">
 The form contains <%= pluralize(@course.errors.count, "error") %>.
 </div>
 <ul>
  <% @course.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
  <% end %>
 </ul>
 </div>
<% end %>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for(@course) do |f| %>
  <%= f.label :course_id, "Course ID"%>
  <%= f.text_field :course_id, disabled:true%>

  <%= f.label :course_title %>
  <%= f.text_field :course_title %>

  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :day_length %>
  <%= f.number_field :day_length %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :level_id %>
  <%= f.number_field :level_id %>

  <%= f.label :category %>
  <%= f.text_field :category %>   

  <%= f.submit "Update Course", class: "btn btn-primary" %>
  <% end %>
 </div>
</div>

<h1></h1>
<%= link_to 'Back', @course, class: "back_btn" %> 
<%= link_to 'All courses', courses_path, class: "back_btn" %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course List</h1>
<%= link_to 'Deleted Course',deleted_path, class: "back_btn" %>
<h1></h1>
<%= will_paginate class: "apple_pagination"%>

<table table class="table table-striped">
  <thead>
    <tr>
      <th>Course ID<%= sort_asc("course_id") %><%= sort_desc("course_id") %></th>
      <th>Course title<%= sort_asc("course_title") %><%= sort_desc("course_title") %></th>
      <th>Topic<%= sort_asc("topic") %><%= sort_desc("topic") %></th>
      <th>Day length<%= sort_asc("day_length") %><%= sort_desc("day_length") %></th>
      <th>Price<%= sort_asc("price") %><%= sort_desc("price") %></th>
      <th>Level<%= sort_asc("level_id") %><%= sort_desc("level_id") %></th>
      <th>Category<%= sort_asc("category") %><%= sort_desc("category") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.course_id, course_path(course, course.course_id) %></td>
        <td><%= course.course_title %></td>
        <td><%= course.topic %></td>
        <td><%= course.day_length %></td>
        <td><%= course.price %></td>
        <td><%= course.level_id %></td>
        <td><%= course.category %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate class: "apple_pagination"%>
<h1></h1>
<%= link_to 'Back', root_path, class: "back_btn"%> 
<%= link_to 'New Course', new_course_path, class: "edit_btn" %>

app/views/courses/new.html.erb
<h1>Create A New Course</h1>

<% if @course.errors.any? %>
 <div id="error_explanation">
 <div class="alert alert-danger">
 The form contains <%= pluralize(@course.errors.count, "error") %>.
 </div>
 <ul>
  <% @course.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
  <% end %>
 </ul>
 </div>
<% end %>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= form_for(@course) do |f| %>
  <%= f.label :course_id, "Courese ID" %>
  <%= f.text_field :course_id %>

  <%= f.label :course_title %>
  <%= f.text_field :course_title %>

  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :day_length %>
  <%= f.number_field :day_length %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :level_id %>
  <%= f.number_field :level_id %>

  <%= f.label :category %>
  <%= f.text_field :category %>   

  <%= f.submit "Create New Course", class: "btn btn-primary" %>
  <% end %>
 </div>
</div>

<%= link_to 'Back', courses_path, class: "back_btn" %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course_ID:</strong>
  <%= @course.course_id %>
</p>

<p>
  <strong>Course title:</strong>
  <%= @course.course_title %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @course.topic %>
</p>

<p>
  <strong>Day length:</strong>
  <%= @course.day_length %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<p>
  <strong>Level:</strong>
  <%= @course.level_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category %>
</p>

  <%= link_to 'Edit', edit_course_path(@course), class: "edit_btn" %> 
  <h6></h6>
  <%= button_to('Delete course', @course, class: "delete_btn", method: :delete, data: {confirm: 'Are you sure to delete the course?', \
    cancel: 'cancel', commit: 'yes'}, title: 'Delete Confirm') %>
  
<%= link_to 'Back', courses_path, class: "back_btn"  %> 


<!--%= link_to 'Delete', course_path(@course), method: :delete, data: {confirm: "Are you sure?"} %-->

app/views/layouts/_footer.html.erb
<footer class="footer center">
 <!--small>
 The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
 by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
 </small!-->
 <nav>
 <ul>
 <li>by @LI JIE</li>
 </ul>
 </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
 <!--[if lt IE 9]>
 <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
 </script>
 <![endif]-->
 </head>
 <body>
 <header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
  <%= link_to "Training DB Webapp", '#', id: "logo" %>
 <nav>
 <ul class="nav navbar-nav navbar-right">
 <li><%= link_to "Top", root_path %></li>
 <li><%= link_to "Create course", create_path %></li>
 <li><%= link_to "All courses", all_path %></li>
 </ul>
 </nav>
 </div>
 </header>
 <div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
 </div>
 </body>
</html>

app/views/toppage/cate_search.html.erb
<h3>Search Result</h3>  

<h5>
<% if @cates_res %>
<span> <%= @cates_res.count %> Courses Found</span>
<% end %>
</h5>

<table table class="table table-striped">
  <thead>
    <tr>
      <th>Course ID</th>
      <th>Course title</th>
      <th>Topic</th>
      <th>Day length</th>
      <th>Price</th>
      <th>Level</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cates_res.each do |result| %> 
      <tr>
        <td><%= link_to result.course_id, result %></td>
        <td><%= result.course_title %></td>
        <td><%= result.topic %></td>
        <td><%= result.day_length %></td>
        <td><%= result.price %></td>
        <td><%= result.level_id %></td>
        <td><%= result.category %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', root_path, class: "back_btn" %>

app/views/toppage/index.html.erb
<!DOCTYPE html>
    <head>
        <!-- jquery -->
        <script src="http://cdn.staticfile.org/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
        <!-- bootstrap -->
        <link href="http://cdn.staticfile.org/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
        <script src="http://cdn.staticfile.org/twitter-bootstrap/3.4.1/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- bootstrap-select -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    </head>

    <div class="contianer text-center">
        <% if flash[:alert] %>
            <div class="alert alert-warning" role="alert">
                <strong><%= flash[:alert] %>!</strong>
                Please input a keyword or choose a category for searching.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>
   
        <style type="text/css">
            body {
            background-image: url("https://en.arij.net/wp-content/uploads/sites/3/2018/07/courseintroimage.jpg");
            background-position: center 0;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            -webkit-background-size: cover;
            -o-background-size: cover;
            -moz-background-size: cover;
            -ms-background-size: cover;
            }
        </style>
    </div>

    <div class="disply-3 font-weight-bold col-lg-4 col-lg-offset-4  \
        col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2 container-fluid col-center-block">
        <h1>Welcome to the Training DB Webapp</h1>
        <div style="text-align:center">
        You can browse all courses or make a simple search by inputting a keyword or choosing a category.
        </div>
        <h3 class="center">SEARCH</h3>

        <div style="width:100%; text-align:center; position:relative">
            <div class="row">
                <!--all search -->
                <%=form_tag(all_path, :method => "get") do%>
                    <%= button_tag " All Courses", :class => 'btn btn-info glyphicon glyphicon-search col-md-offset-3 col-md-6',:name => nil%>  
                <% end %>
            </div>
            <h1></h1>
            <div class="form-group col-md-offset-2 col-md-8"> 
                <!--keyword search -->
                <%= form_tag("/search", :method => :get, class: 'form-inline') do%>
                    <div class="input-group ">  
                        <%= search_field_tag :search, params[:search], placeholder: "Keyword", class: "form-control" %>   
                        <span class="input-group-btn">
                            <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
                        </span>  
                    </div> 
                <% end %>
            </div>

            <div class="form-group">
                <div class="row-fluid col-md-offset-2 col-md-8">
                    <!---category search -->
                    <%= form_tag(cate_search_path, :method => "get") do%>
                        <!--name defines params-->
                        <select name ="category_name" data-size="10" class="selectpicker show-tick form-control" title="Choose Category" data-live-search="true">   
                            <% @cates.each do |cate| %>
                                <li>
                                    <option ><%= cate.category %> </option>
                                </li>
                            <% end %>
                        </select>
                        <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil%>       
                    <% end %>
                </div>
            </div>
        </div>

    </div>
    </div>

</html>

app/views/toppage/search.html.erb
<h3>Search Result</h3>  

<h5>
<% if @keyword_results %>
  <span> <%= @keyword_results.count %> Courses Found</span>
<% end %>
</h5>

<table table class="table table-striped">
  <thead>
    <tr>
      <th>Course ID</th>
      <th>Course title</th>
      <th>Topic</th>
      <th>Day length</th>
      <th>Price</th>
      <th>Level</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @keyword_results.each do |result| %> 
        <tr>
          <td><%= link_to result.course_id, result %></td>
          <td><%= result.course_title %></td>
          <td><%= result.topic %></td>
          <td><%= result.day_length %></td>
          <td><%= result.price %></td>
          <td><%= result.level_id %></td>
          <td><%= result.category %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<%= link_to 'Back', root_path, class: "back_btn" %>